### PR TITLE
fix backup script misses upstream on install

### PR DESCRIPTION
**Pull request by 3DPrintingGeek**
After installing the script, no files were backed-up to the repository.
This was caused by the variable BRANCH that was initially set to "".
That caused no upstream could be set, and so no files were backed up.
As a simple fix the BRANCH is set to be "main".

### CODE REVIEW

**Comment by Guilouz** [comment]
Can you try the new change i have made to git backup. Now branch name is asked during configuration.

This allows to choose branch.

**Comment by 3DPrintingGeek** [comment]
Sure. I'll try it. Sounds like a good idea. I thought about that, as well. By having a way to specify the branch name, one can create one repo, and backup the configs of different printers each to own branch.

**Comment by 3DPrintingGeek** [comment]
Hi @Guilouz, I checked out the updated branch.
I fixed a little problem preventing the push of the initial backup to the remote during installation.
Everything else seems to work fine.

**Comment by Guilouz** [comment]
Can't merge this, you have not removed the defined main branch.

I have fixed missing REPO_BRANCH.

Thanks for your intervention.

**Pull request closed without merging**
