### PR TITLE
Add OctoApp support

### PR DESCRIPTION
**Pull request by crysxd**
This adds support for the OctoApp Companion plugin. I tested everything on a Nebula Pad, but as my plugin is based on OctoEverywhere and I copied over the OctoEverywhere parts of this script, I do not expect any hickups on other machines either :)

### CODE REVIEW

**Comment by crysxd** [comment]
Thank you @Guilouz! :)

**Comment by Guilouz** [comment]
@crysxd There is an issue with you uninstaller, it restart install before:

Capture d’écran 2024-03-30 à 18 52 25

**Comment by Guilouz** [comment]
And report errors: 

Capture d’écran 2024-03-30 à 18 53 39

**Comment by Guilouz** [comment]
Maybe you can check how mobileraker companion is working, it have a better installer and uninstaller.

**Comment by crysxd** [comment]
Thanks for the feedback! The problem is that the actual installer is in Python, so I need to bootstrap the environment first...I can defenitly skip the optional pycryptdome, though. That's also the one that gives an error on some machines, that's why I made it optional. The K1 machines are affected by this as well....

The OctoEverywhere uninstaller works the same way btw

**Pull request merged**
