### PR TITLE
Conflict between PAUSE and M600

### PR DESCRIPTION
**Pull request by ElForastero**
I noticed that if I'm using just a multicolor print itself, everything is fine.

But recently I was in need of a `PAUSE` on a certain layers and I discovered a buggy behaviour: before extruding a new filament Z axis moves to the last safe position and only then extruder starts purging a new filament. 

Let's consider the following scenario:
1. `PAUSE` is used on a 5th layer
2. `M600` is used on a 10th layer

In such a case, `PAUSE` macro [writes `z_safe_pause`position](https://github.com/Guilouz/Creality-K1-Extracted-Firmwares/blob/210827331fdd1ad7987971a8be9e5ee6aa0ef79f/Firmware/usr/share/klipper/config/K1_CR4CU220812S10/gcode_macro.cfg#L308).

Now `M600` on a 10th layer works fine, but `RESUME` doesn't. `RESUME` reads the last `z_safe_pause` written by `PAUSE` on 5th layer and since it's defined it tries to perform a Z movement to the 5th (?) layer (not sure 5th or 10th actually, but it moves - that's the fact).

And when the nozzle is 1cm above the heating bed it starts exrtuding tons of filament that doesn't fit into such a small gap.

This happens only when a `PAUSE` macro (not `M600`) was used before `M600`.

In attempts to debug this I found that the issue is caused by:
1. `M600` macro not updating `z_safe_pause` position like a regular `PAUSE` does
2. `RESUME` probably shouldn't contain those `Z` movement before extruding at all

Extrusion should always happen from the distance to have enough space for a waste.

### CODE REVIEW

**Comment by Guilouz** [comment]
Your changes have no sense, you add a saving variable in M600 macro but you not reuse it on resume (you have removed it).

Normally just add SET_GCODE_VARIABLE MACRO=PRINTER_PARAM VARIABLE=z_safe_pause VALUE={z_safe|float} in M600 macro do the trick.

**Comment by ElForastero** [comment]
> Your changes have no sense, you add a saving variable in M600 macro but you not reuse it on resume (you have removed it).
> 
> 
> 
> Normally just add SET_GCODE_VARIABLE MACRO=PRINTER_PARAM VARIABLE=z_safe_pause VALUE={z_safe|float} in M600 macro do the trick.

I'll try one more time, but I remember I did it and with no success - RESUME will move Z 1cm above the plate anyway.

Maybe it's better to remove Z movement before extrusion at all?

**Comment by ElForastero** [comment]
Oh, maybe we should hide a Z movement under a M600_state check?

If it's an M600 - no movements, otherwise go on

**Comment by ElForastero** [comment]
The interesting and at the same time confusing part here is that even without that G1 command for Z axis everything works as a charm.

Don't Creality have some logic in the base RESUME macro?

**Comment by Guilouz** [comment]
Can you try the last change i have made on m600 feature

**Comment by ElForastero** [comment]
I'm away from my K1 till the next week. Let's wait a bit and I will check it

**Comment by ElForastero** [comment]
@Guilouz I did a check with the updated script version and the issue is still there

Have a look at what I mean: https://www.youtube.com/watch?v=1CREKy7IFVw

I marked key moments with timestamps.

My thoughts are that we should hide this Z movement under an `if` statement to avoid it during filament changes. It's redundant in the case. As I understand, `RESUME_BASE` macro itself is responsible for bringing Z back to the safe position.

UPD:

I made a change I mentioned (hiding Z movement under a condition). Now everything works as expected.
Have a look: https://www.youtube.com/watch?v=L7ByJSwQUuQ

[Cylinder_PETG_3m49s.gcode.zip](https://github.com/Guilouz/Creality-Helper-Script/files/14820782/Cylinder_PETG_3m49s.gcode.zip)

UPD2:

I would also like to reduce the extrusion on filament change. I have tried to reduce it twice from E180 to E90 and I think 90 is enough. 180 produces too much waste. But this is a different story not related to this MR.

<details>
<summary>E90 vs E180</summary>

</details>

**Comment by Guilouz** [comment]
Thanks for this. I don't understand why I put 180, originally I wanted to put 100.

The idea is to put enough purge for the change from one color to another such as from black to white for example, to be sure that there is no trace of black remaining and that the white is pure.

**Pull request merged**
